import { DownloadPlatform, UpcomingFeature, SampleVideo } from './types';

export const DOWNLOAD_PLATFORMS: DownloadPlatform[] = [
  {
    id: 'mac-arm',
    name: 'MacBook M Series',
    architecture: 'Apple Silicon (M1, M2, M3, M4)',
    platformCategory: 'macos-m',
    fileFormat: '.dmg (Native ARM64)',
    fileSize: '172.4 MB',
    version: 'v1.4.2',
    status: 'available',
    releaseDate: 'Latest Stable Build',
    requirements: 'macOS 12.0 Monterey or higher',
    checksum: 'sha256: 4c43da0cf6adf3adc4d182b839e8873f7f0a20894580afcfc3402183ae8acb2e',
    downloadUrl: 'https://github.com/mohammadazam-cyber/framegrab/releases/latest/download/FrameGrab-Standalone-Apple-Silicon.dmg',
    iconType: 'apple',
    features: [
      'Hardware-accelerated HEVC/ProRes decoding',
      'Ultra-low memory footprint (<48MB RAM)',
      'Native Apple Silicon metal optimizations',
      'Background daemon with zero fan spin',
    ],
  },
  {
    id: 'mac-intel',
    name: 'MacBook Intel Series',
    architecture: 'Intel Core 64-bit (x86_64)',
    platformCategory: 'macos-intel',
    fileFormat: '.dmg (x86_64)',
    fileSize: '38.6 MB',
    version: 'v1.4.2',
    status: 'available',
    releaseDate: 'Latest Stable Build',
    requirements: 'macOS 11.0 Big Sur or higher',
    checksum: 'sha256: 4e91a0293dbb7c05001cfa7521a0081d4399e2908ff91',
    downloadUrl: '#download-mac-intel',
    iconType: 'apple',
    features: [
      'Optimized SSE4/AVX2 multi-threading',
      'Full backwards compatibility with older Macs',
      'Lossless stream extraction engine',
      'Stand-alone DMG installer',
    ],
  },
  {
    id: 'windows-os',
    name: 'Windows Edition',
    architecture: 'Windows 10 & 11 (x64 / ARM64)',
    platformCategory: 'windows',
    fileFormat: '.exe / .msi Installer',
    fileSize: '41.0 MB (Est.)',
    version: 'v1.5.0 Preview',
    status: 'coming_soon',
    releaseDate: 'Q2 2026 Target',
    requirements: 'Windows 10 Build 19041+ or Windows 11',
    iconType: 'windows',
    features: [
      'Native Windows Fluent UI aesthetic',
      'DirectX 12 video pipeline integration',
      'Shell context-menu right-click grabber',
      'System tray quick-download daemon',
    ],
  },
  {
    id: 'chrome-ext',
    name: 'Chrome Extension',
    architecture: 'Chromium Manifest V3',
    platformCategory: 'chrome',
    fileFormat: '.crx / Chrome Web Store',
    fileSize: '2.1 MB',
    version: 'v1.0.0 Beta',
    status: 'coming_soon',
    releaseDate: 'Store Review in Progress',
    requirements: 'Chrome, Brave, Edge, Opera, Arc',
    iconType: 'chrome',
    features: [
      '1-Click floating overlay on any active video player',
      'Automatic highest-resolution stream sniffer',
      'Direct download or handoff to desktop app',
      'Zero telemetry, 100% client-side privacy',
    ],
  },
];

export const UPCOMING_FEATURES: UpcomingFeature[] = [
  {
    id: 'feat-any-site',
    title: 'Download Any Video from Any Website',
    badge: 'Universal Core',
    description: 'Deep DOM inspection and network sniffing to isolate embedded video streams, m3u8 playlists, blob URLs, and custom web players from virtually any webpage.',
    iconName: 'Globe',
    supportedFormats: ['m3u8', 'MP4', 'WebM', 'Blob URLs', 'HLS Streams'],
    status: 'Alpha Testing',
    highlight: true,
  },
  {
    id: 'feat-instagram',
    title: 'Instagram Downloader Engine',
    badge: 'Social Core',
    description: 'Seamlessly extract 1080p Instagram Reels, main feed carousel video galleries, audio tracks, and expiring Stories without login constraints or watermarks.',
    iconName: 'Instagram',
    supportedFormats: ['Reels', 'Feed Videos', 'Carousels', 'Stories', 'Audio'],
    status: 'In Development',
  },
  {
    id: 'feat-facebook',
    title: 'Facebook HD & 4K Grabber',
    badge: 'High Bitrate',
    description: 'Direct parser for high-definition Facebook Watch videos, public group uploads, reels, and live stream replays at the source upload bitrate.',
    iconName: 'Facebook',
    supportedFormats: ['1080p HD', '4K Watch', 'FB Reels', 'Live Archives'],
    status: 'In Development',
  },
  {
    id: 'feat-pinterest',
    title: 'Pinterest Video Pin Extractor',
    badge: 'Lossless Visuals',
    description: 'Instant lossless capture for Pinterest video pins, Idea pins, DIY tutorials, and moodboard clips in native crystal-clear MP4 resolution.',
    iconName: 'Pin',
    supportedFormats: ['Video Pins', 'Idea Pins', 'MP4 Full-Res'],
    status: 'In Development',
  },
  {
    id: 'feat-audio-stems',
    title: '1-Click Audio & Stem Extractor',
    badge: 'Hi-Res Audio',
    description: 'Strip clean audio tracks from any video and export directly to MP3 (320kbps), AAC, WAV, or pristine FLAC format for sampling and offline listening.',
    iconName: 'Music',
    supportedFormats: ['MP3 320kbps', 'FLAC', 'AAC', 'WAV Lossless'],
    status: 'Planned',
  },
  {
    id: 'feat-subtitles',
    title: 'Multi-Language Subtitle Parser',
    badge: 'Accessibility',
    description: 'Auto-detect and package embedded or external closed captions into clean .SRT, .VTT, or hardcoded burned-in video subtitles.',
    iconName: 'Subtitles',
    supportedFormats: ['.SRT', '.VTT', '.ASS', 'Burned-in Subtitles'],
    status: 'Planned',
  },
  {
    id: 'feat-batch',
    title: 'Multi-Stream Batch Queue',
    badge: 'Power Workflow',
    description: 'Paste a list of 50+ URLs or full channel/playlist feeds to download in parallel with custom filename patterns and speed throttling.',
    iconName: 'ListOrdered',
    supportedFormats: ['Playlists', 'Multi-link Batch', 'Auto-naming'],
    status: 'Planned',
  },
  {
    id: 'feat-hdr-8k',
    title: '8K HDR & Dolby Vision Passthrough',
    badge: 'Pro Quality',
    description: 'True bit-for-bit passthrough ensuring 10-bit color, 60/120fps high frame rates, and wide color gamuts remain unaltered.',
    iconName: 'Sparkles',
    supportedFormats: ['8K UHD', '4K 60fps', 'HDR10', 'Dolby Vision'],
    status: 'In Development',
  },
];

export const SAMPLE_VIDEOS: SampleVideo[] = [
  {
    id: 'sample-insta',
    title: 'Cinematic Tokyo Street Photography Reel',
    platform: 'Instagram',
    originalUrl: 'https://instagram.com/reel/C89qXZL...',
    duration: '0:42',
    thumbnail: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600&auto=format&fit=crop&q=80',
    resolution: '1080 x 1920 (9:16 Vertical)',
    fileSize: '24.8 MB',
    streams: [
      { quality: '1080p (Source HD)', format: 'MP4 / H.264', size: '24.8 MB', bitrate: '4.8 Mbps', hasAudio: true },
      { quality: '720p (Compressed)', format: 'MP4 / H.264', size: '12.1 MB', bitrate: '2.4 Mbps', hasAudio: true },
      { quality: 'Audio Only', format: 'M4A / 256kbps', size: '1.4 MB', bitrate: '256 kbps', hasAudio: true },
    ],
  },
  {
    id: 'sample-fb',
    title: 'Nordic Architecture Documentary Snippet',
    platform: 'Facebook',
    originalUrl: 'https://facebook.com/watch/?v=98214309...',
    duration: '2:15',
    thumbnail: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    resolution: '3840 x 2160 (4K UHD 16:9)',
    fileSize: '142.3 MB',
    streams: [
      { quality: '2160p (4K UHD 60fps)', format: 'MP4 / HEVC', size: '142.3 MB', bitrate: '18.2 Mbps', hasAudio: true },
      { quality: '1080p (Full HD)', format: 'MP4 / H.264', size: '48.6 MB', bitrate: '6.0 Mbps', hasAudio: true },
      { quality: '720p (HD)', format: 'MP4 / H.264', size: '22.0 MB', bitrate: '2.8 Mbps', hasAudio: true },
      { quality: 'Audio Only', format: 'MP3 / 320kbps', size: '5.2 MB', bitrate: '320 kbps', hasAudio: true },
    ],
  },
  {
    id: 'sample-pinterest',
    title: 'Minimalist Interior Lighting Aesthetics',
    platform: 'Pinterest',
    originalUrl: 'https://pinterest.com/pin/1094328498...',
    duration: '0:18',
    thumbnail: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    resolution: '1080 x 1350 (4:5 Portrait)',
    fileSize: '16.4 MB',
    streams: [
      { quality: '1080p (Full Res Pin)', format: 'MP4 / H.264', size: '16.4 MB', bitrate: '5.2 Mbps', hasAudio: true },
      { quality: '720p (Standard)', format: 'MP4 / H.264', size: '7.8 MB', bitrate: '2.5 Mbps', hasAudio: true },
    ],
  },
  {
    id: 'sample-web',
    title: 'Web Stream Live Video Feed (m3u8/HLS)',
    platform: 'Universal Web',
    originalUrl: 'https://stream.example.org/live/manifest.m3u8',
    duration: '5:30',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    resolution: '1920 x 1080 (1080p 60fps)',
    fileSize: '89.5 MB',
    streams: [
      { quality: '1080p60 (HLS Stream Merged)', format: 'MP4 / H.264', size: '89.5 MB', bitrate: '7.5 Mbps', hasAudio: true },
      { quality: '720p60 (Fast Stream)', format: 'MP4 / H.264', size: '42.1 MB', bitrate: '3.6 Mbps', hasAudio: true },
      { quality: 'WAV Master Audio', format: 'WAV / 24-bit', size: '28.4 MB', bitrate: '1411 kbps', hasAudio: true },
    ],
  },
];
